language: erlang
notifications:
  recipients:
    - eric.meadows.jonsson@gmail.com
otp_release:
  - R16B
before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir && make && cd ..
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - sudo env PATH=$PATH elixir test/travis_setup.exs
  - MIX_ENV=test mix do deps.get, compile
script:
  - mix test

